export const AUDIT_ACTIONS = {

    USER_REGISTERED:
        "USER_REGISTERED",

    ORGANIZATION_CREATED:
        "ORGANIZATION_CREATED",

    MEMBER_INVITED:
        "MEMBER_INVITED",

    MEMBER_REMOVED:
        "MEMBER_REMOVED",

    MEMBER_ROLE_CHANGED:
        "MEMBER_ROLE_CHANGED",

    TEAM_CREATED:
        "TEAM_CREATED",

    TEAM_UPDATED:
        "TEAM_UPDATED",

    TEAM_DELETED:
        "TEAM_DELETED",

    TEAM_MEMBER_ADDED:
        "TEAM_MEMBER_ADDED",

    TEAM_MEMBER_REMOVED:
        "TEAM_MEMBER_REMOVED",

    API_KEY_CREATED:
        "API_KEY_CREATED",

    API_KEY_UPDATED:
        "API_KEY_UPDATED",

    API_KEY_ROTATED:
        "API_KEY_ROTATED",

    API_KEY_REVOKED:
        "API_KEY_REVOKED",

    API_KEY_ARCHIVED:
        "API_KEY_ARCHIVED"
};