export const AUDIT_ACTIONS = {

    USER_REGISTERED:
        "USER_REGISTERED",

    ORGANIZATION_CREATED:
        "ORGANIZATION_CREATED",

    MEMBER_INVITED:
        "MEMBER_INVITED",

    MEMBER_REMOVED:
        "MEMBER_REMOVED",

    MEMBER_ROLE_CHANGED:
        "MEMBER_ROLE_CHANGED",

    PROJECT_CREATED:
        "PROJECT_CREATED",

    PROJECT_UPDATED:
        "PROJECT_UPDATED",

    PROJECT_DELETED:
        "PROJECT_DELETED",

    PROJECT_MEMBER_ADDED:
        "PROJECT_MEMBER_ADDED",

    PROJECT_MEMBER_REMOVED:
        "PROJECT_MEMBER_REMOVED",

    API_KEY_CREATED:
        "API_KEY_CREATED",

    API_KEY_UPDATED:
        "API_KEY_UPDATED",

    API_KEY_ROTATED:
        "API_KEY_ROTATED",

    API_KEY_REVOKED:
        "API_KEY_REVOKED",

    API_KEY_ARCHIVED:
        "API_KEY_ARCHIVED",

    INVITATION_ACCEPTED:
        "INVITATION_ACCEPTED",

    INVITATION_REJECTED:
        "INVITATION_REJECTED"
};